app = "dnd-dm-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python main.py"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[deploy]
  strategy = "immediate"